using System.Windows.Media;
using MaterialDesignColors;

namespace v2rayN.Common;

/// <summary>
/// NiN's own accent swatches, shown in the "Color" dropdown of the theme settings.
/// </summary>
/// <remarks>
/// MaterialDesign's built-in <c>SwatchesProvider</c> only offers the standard Material
/// palette. These are custom brand colours, so they are built here with the same
/// <see cref="Hue"/> shade ramp the Material themes expect: the theme reads
/// <c>ExemplarHue</c> for the primary colour and derives hover/pressed shades from
/// the remaining hues, so a full ramp is required for the highlight states to be
/// generated rather than falling back to grey.
///
/// Every colour carries its own readable foreground: the palette spans light olive
/// and mauve through dark navy and wine, so a single hardcoded foreground would be
/// unreadable on two of the seven.
/// </remarks>
internal static class NiNSwatches
{
    private sealed record NiNColor(string Name, string Hex, string Foreground);

    // The two light colours (Olive, Mauve) need dark text: white on them is only
    // 2.6:1 / 2.9:1. The rest are dark enough for white.
    private static readonly NiNColor[] Palette =
    [
        new("NiN Olive", "97A87A", "000000"),
        new("NiN Teal Blue", "2D7495", "FFFFFF"),
        new("NiN Steel Blue", "455B8A", "FFFFFF"),
        new("NiN Deep Green", "2A6B5C", "FFFFFF"),
        new("NiN Wine", "972828", "FFFFFF"),
        new("NiN Mauve", "A290B7", "000000"),
        new("NiN Crimson", "CB2957", "FFFFFF"),
    ];

    public static IEnumerable<Swatch> Build()
    {
        foreach (var item in Palette)
        {
            var hue = Parse(item.Hex);
            var foreground = Parse(item.Foreground);
            yield return new Swatch(item.Name, Hues(hue, foreground), Hues(hue, foreground));
        }
    }

    /// <summary>
    /// The shade ramp Material Design uses: 50..900 around the supplied 500 colour.
    /// Generated by mixing towards white then black so the exemplar stays exactly
    /// the requested hex rather than drifting.
    /// </summary>
    private static IList<Hue> Hues(Color baseColor, Color foreground)
    {
        // Index in this list is the Material shade; the 500 entry is the real colour.
        var mixWhite = new[] { 0.88, 0.72, 0.56, 0.34, 0.16, 0.00, 0.00, 0.12, 0.26, 0.40 };
        var names = new[] { "50", "100", "200", "300", "400", "500", "600", "700", "800", "900" };

        var list = new List<Hue>(names.Length);
        for (var i = 0; i < names.Length; i++)
        {
            var amount = mixWhite[i];
            // Negative means darken instead of lighten.
            var color = amount >= 0
                ? Mix(baseColor, Colors.White, amount)
                : Mix(baseColor, Colors.Black, -amount);
            list.Add(new Hue(names[i], color, foreground));
        }
        return list;
    }

    private static Color Mix(Color from, Color to, double ratio)
    {
        var r = (byte)Math.Round(from.R + (to.R - from.R) * ratio);
        var g = (byte)Math.Round(from.G + (to.G - from.G) * ratio);
        var b = (byte)Math.Round(from.B + (to.B - from.B) * ratio);
        return Color.FromRgb(r, g, b);
    }

    private static Color Parse(string hex)
    {
        var span = hex.AsSpan();
        return Color.FromRgb(
            byte.Parse(span[..2], System.Globalization.NumberStyles.HexNumber),
            byte.Parse(span[2..4], System.Globalization.NumberStyles.HexNumber),
            byte.Parse(span[4..6], System.Globalization.NumberStyles.HexNumber));
    }
}
